# This is a basic workflow to help you get started with Actions

name: VAULT_CI_DEMO

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  retrieve_vault_secrets:
      runs-on: ubuntu-latest
      permissions:
        id-token: write  # Note: this permission is explicitly required for Vault auth
        contents: read

      steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.3.1
        with:
          url: https://vault-cluster.vault.11eb13c6-5c7e-9b94-9eb3-0242ac110018.aws.hashicorp.cloud:8200
          role: github-actions-job
          method: jwt
          #jwtGithubAudience: sigstore # set the GitHub token's aud claim
          secrets: |
                    kv/data/vault-action-demo     accessKey   | AWS_ACCESS_KEY_ID ;
                    kv/data/ci/vault-action-demo  secretKey   | AWS_SECRET_ACCESS_KEY ;

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest




    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
